/*
 * My Pokedex API
 * Some custom description of API.
 *
 * OpenAPI spec version: API TOS
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Pokemon
 */


public class Pokemon {
  @SerializedName("alola")
  private Boolean alola = null;

  @SerializedName("amount")
  private Integer amount = null;

  @SerializedName("crypto")
  private Boolean crypto = null;

  @SerializedName("galarian")
  private Boolean galarian = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("legendary")
  private Boolean legendary = null;

  @SerializedName("lucky")
  private Boolean lucky = null;

  @SerializedName("mystic")
  private Boolean mystic = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("normal")
  private Boolean normal = null;

  @SerializedName("pokedexNr")
  private Integer pokedexNr = null;

  @SerializedName("purified")
  private Boolean purified = null;

  @SerializedName("shiny")
  private Boolean shiny = null;

  @SerializedName("traded")
  private Boolean traded = null;

  public Pokemon alola(Boolean alola) {
    this.alola = alola;
    return this;
  }

   /**
   * Get alola
   * @return alola
  **/
  @Schema(description = "")
  public Boolean isAlola() {
    return alola;
  }

  public void setAlola(Boolean alola) {
    this.alola = alola;
  }

  public Pokemon amount(Integer amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @Schema(description = "")
  public Integer getAmount() {
    return amount;
  }

  public void setAmount(Integer amount) {
    this.amount = amount;
  }

  public Pokemon crypto(Boolean crypto) {
    this.crypto = crypto;
    return this;
  }

   /**
   * Get crypto
   * @return crypto
  **/
  @Schema(description = "")
  public Boolean isCrypto() {
    return crypto;
  }

  public void setCrypto(Boolean crypto) {
    this.crypto = crypto;
  }

  public Pokemon galarian(Boolean galarian) {
    this.galarian = galarian;
    return this;
  }

   /**
   * Get galarian
   * @return galarian
  **/
  @Schema(description = "")
  public Boolean isGalarian() {
    return galarian;
  }

  public void setGalarian(Boolean galarian) {
    this.galarian = galarian;
  }

  public Pokemon id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Pokemon legendary(Boolean legendary) {
    this.legendary = legendary;
    return this;
  }

   /**
   * Get legendary
   * @return legendary
  **/
  @Schema(description = "")
  public Boolean isLegendary() {
    return legendary;
  }

  public void setLegendary(Boolean legendary) {
    this.legendary = legendary;
  }

  public Pokemon lucky(Boolean lucky) {
    this.lucky = lucky;
    return this;
  }

   /**
   * Get lucky
   * @return lucky
  **/
  @Schema(description = "")
  public Boolean isLucky() {
    return lucky;
  }

  public void setLucky(Boolean lucky) {
    this.lucky = lucky;
  }

  public Pokemon mystic(Boolean mystic) {
    this.mystic = mystic;
    return this;
  }

   /**
   * Get mystic
   * @return mystic
  **/
  @Schema(description = "")
  public Boolean isMystic() {
    return mystic;
  }

  public void setMystic(Boolean mystic) {
    this.mystic = mystic;
  }

  public Pokemon name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Pokemon normal(Boolean normal) {
    this.normal = normal;
    return this;
  }

   /**
   * Get normal
   * @return normal
  **/
  @Schema(description = "")
  public Boolean isNormal() {
    return normal;
  }

  public void setNormal(Boolean normal) {
    this.normal = normal;
  }

  public Pokemon pokedexNr(Integer pokedexNr) {
    this.pokedexNr = pokedexNr;
    return this;
  }

   /**
   * Get pokedexNr
   * @return pokedexNr
  **/
  @Schema(description = "")
  public Integer getPokedexNr() {
    return pokedexNr;
  }

  public void setPokedexNr(Integer pokedexNr) {
    this.pokedexNr = pokedexNr;
  }

  public Pokemon purified(Boolean purified) {
    this.purified = purified;
    return this;
  }

   /**
   * Get purified
   * @return purified
  **/
  @Schema(description = "")
  public Boolean isPurified() {
    return purified;
  }

  public void setPurified(Boolean purified) {
    this.purified = purified;
  }

  public Pokemon shiny(Boolean shiny) {
    this.shiny = shiny;
    return this;
  }

   /**
   * Get shiny
   * @return shiny
  **/
  @Schema(description = "")
  public Boolean isShiny() {
    return shiny;
  }

  public void setShiny(Boolean shiny) {
    this.shiny = shiny;
  }

  public Pokemon traded(Boolean traded) {
    this.traded = traded;
    return this;
  }

   /**
   * Get traded
   * @return traded
  **/
  @Schema(description = "")
  public Boolean isTraded() {
    return traded;
  }

  public void setTraded(Boolean traded) {
    this.traded = traded;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pokemon pokemon = (Pokemon) o;
    return Objects.equals(this.alola, pokemon.alola) &&
        Objects.equals(this.amount, pokemon.amount) &&
        Objects.equals(this.crypto, pokemon.crypto) &&
        Objects.equals(this.galarian, pokemon.galarian) &&
        Objects.equals(this.id, pokemon.id) &&
        Objects.equals(this.legendary, pokemon.legendary) &&
        Objects.equals(this.lucky, pokemon.lucky) &&
        Objects.equals(this.mystic, pokemon.mystic) &&
        Objects.equals(this.name, pokemon.name) &&
        Objects.equals(this.normal, pokemon.normal) &&
        Objects.equals(this.pokedexNr, pokemon.pokedexNr) &&
        Objects.equals(this.purified, pokemon.purified) &&
        Objects.equals(this.shiny, pokemon.shiny) &&
        Objects.equals(this.traded, pokemon.traded);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alola, amount, crypto, galarian, id, legendary, lucky, mystic, name, normal, pokedexNr, purified, shiny, traded);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pokemon {\n");
    
    sb.append("    alola: ").append(toIndentedString(alola)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    crypto: ").append(toIndentedString(crypto)).append("\n");
    sb.append("    galarian: ").append(toIndentedString(galarian)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    legendary: ").append(toIndentedString(legendary)).append("\n");
    sb.append("    lucky: ").append(toIndentedString(lucky)).append("\n");
    sb.append("    mystic: ").append(toIndentedString(mystic)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    normal: ").append(toIndentedString(normal)).append("\n");
    sb.append("    pokedexNr: ").append(toIndentedString(pokedexNr)).append("\n");
    sb.append("    purified: ").append(toIndentedString(purified)).append("\n");
    sb.append("    shiny: ").append(toIndentedString(shiny)).append("\n");
    sb.append("    traded: ").append(toIndentedString(traded)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
